stages:
  # - configure
  - deploy

default:
  tags:
    - practice
  before_script:
    - echo "------ Install Ansible ------"
    - apk update
    - apk add --no-cache ansible
    - rm -rf /var/cache/apk/*

# variables:
#   TEST: test

# configure:
#   stage: configure
#   only:
#     - main
#   script:
#     - ansible-playbook -i hosts.ini ansible/deploy.yml -t configure -v -D

deploy:
  stage: deploy
  only:
    - main
  script:
    - cd ansible/
    - ansible-playbook -i hosts.ini deploy.yml -v -D
