stages:
  - deploy

default:
  tags:
    - practice
  before_script:
    - echo "------ Install python3 ------"
    - apk update
    - apk add --no-cache gcc python3 py3-pip
    - rm -rf /var/cache/apk/*
    - echo "------ Install Ansible ------"
    - python3 -m pip install --upgrade pip
    - python3 -m pip install ansible
    - ansible-galaxy collection install community.docker
    - ansible --version
    - docker info

variables:
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_PIPELINING: "True"
deploy:
  stage: deploy
  only:
    - main
  script:
    - ansible-playbook -i ansible/hosts.ini ansible/deploy.yml -v -D
