stages:
  - deploy

default:
  tags:
    - practice
  before_script:
    - echo "------ Install Ansible ------"
    - apk update
    - apk add --no-cache ansible
    - rm -rf /var/cache/apk/*
    - ansible-galaxy collection install community.docker
    - pip install requests

variables:
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_PIPELINING: "True"
  IMAGE_NAME: practice-app
  IMAGE_TAG: v1
deploy:
  stage: deploy
  only:
    - main
  script:
    - docker info
    - ansible-playbook -i ansible/hosts.ini ansible/deploy.yml -v -D
