stages:
  - lint
  - build
  - deploy

default:
  tags:
    - practice
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  before_script:
    - echo "------ Install Ansible ------"
    - apk update
    - apk add --no-cache ansible ansible-lint
    - ansible --version
    - docker info

variables:
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_PIPELINING: "True"
  IMAGE_NAME: practice
  IMAGE_TAG: v1
  APP_PORT: 5000

ansible-lint:
  stage: lint
  script:
    - ansible-lint -v ansible/*.yml ansible/*/*.yml
  only:
    changes:
      - ansible/*

build:
  stage: build
  only:
    - main
  script:
    - docker build --tag ${IMAGE_NAME}:${IMAGE_TAG} app/
    - docker run --rm -d -p 5000 -e APP_PORT=${APP_PORT} --name ${IMAGE_NAME} ${IMAGE_NAME}:${IMAGE_TAG}
    - docker stop ${IMAGE_NAME}
    - |
      if [ -n ${REGISTRY_USER} ] && [ -n ${REGISTRY_PASSWORD} ]; then
        docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
        echo "Pushing image to ${REGISTRY_USER}/${IMAGE_NAME}:${IMAGE_TAG}"
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_USER}/${IMAGE_NAME}:${IMAGE_TAG}
        docker push ${REGISTRY_USER}/${IMAGE_NAME}:${IMAGE_TAG}
      fi
  rules:
    - changes:
        - app/*

deploy:
  stage: deploy
  only:
    - main
  when: manual
  script:
    - ansible-playbook -i ansible/hosts.ini ansible/deploy.yml -v -D
  rules:
    - changes:
        - app/*
