stages:
  - deploy

default:
  tags:
    - practice
  before_script:
    - echo "------ Install Ansible ------"
    - apk update
    - apk add --no-cache ansible
    - rm -rf /var/cache/apk/*

deploy:
  stage: deploy
  only:
    - main
  script:
    - cd ansible/
    - ansible-playbook -i hosts.ini deploy.yml -v -D
