stages:
  - deploy

default:
  image: alpine/ansible:2.14.5
  tags:
    - practice
  before_script:
    - echo "------ Install Ansible Collection ------"
    - ansible-galaxy collection install community.docker
    - ansible --version
    - echo "------ Install Docker CLI ------"
    - apk update
    - apk add --no-cache docker-cli
    - docker info

variables:
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_PIPELINING: "True"
deploy:
  stage: deploy
  only:
    - main
  script:
    - ansible-playbook -i ansible/hosts.ini ansible/deploy.yml -v -D
