packages:
  - python3
  - py3-pip
  - git

git_repo_clone_url: http://gitlab-web/practice/automation.git
git_repo_clone_dest: /opt/automation

base_dir: /builds/practice/automation
app_requirements_file: "{{ base_dir }}/requirements.txt"
app_path: "{{ base_dir }}/app.py"
