packages:
  - python3
  - py3-pip
  - git

git_repo_clone_url: http://gitlab-web/practice/automation.git
git_repo_clone_dest: /opt/automation

app_requirements_file: "../requirements.txt"
app_path: "../app.py"
