---
- name: Deploy Python Application
  hosts: all
  become: true
  vars_files:
    - vars/myvars.yml
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      when:
        - packages is defined
        - packages is iterable
        - packages | length > 1
      loop: "{{ packages }}"
      tags:
        - configure

    - name: Deploy app
      when:
        - registry_user is defined
        - registry_password is defined
      tags:
        - deploy
      block:
        - name: Set full image name
          ansible.builtin.set_fact:
            app_image_full: "{{ registry_user }}/{{ app_image_name }}:{{ app_image_tag }}"

        - name: Login to Docker Hub
          ansible.builtin.command:
            cmd: docker login -u {{ registry_user }} -p {{ registry_password }}
          register: docker_login_result
          changed_when: docker_login_result.rc != 0

        - name: Pull docker image
          ansible.builtin.command:
            cmd: docker pull {{ app_image_full }}
          register: docker_pull_result
          changed_when: docker_pull_result.rc != 0

        - name: Start docker container
          ansible.builtin.command:
            cmd: docker run -d --restart=always -p {{ app_port }}:{{ app_port }} --name {{ app_image_name }} {{ app_image_full }}
          register: docker_run_result
          changed_when: docker_run_result.rc != 0
