---
- name: Deploy Python Application
  hosts: all
  become: yes
  vars_files:
    - vars/myvars.yml
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      when:
        - packages is defined
        - packages is iterable
        - packages | length > 1
      loop: "{{ packages }}"
      tags:
        - configure
